<?php echo $this->headScript()->prependFile($this->baseUrl().'/templates/admin/js/process.js'); ?>


<div id="toolbar-box">
<div class="t">
<div class="t">
<div class="t"></div>
</div>
</div>
<div class="m">
<div id="toolbar" class="toolbar-list">
<ul>
	<li id="toolbar-new" class="button"><a class="toolbar"
		href="<?php echo $this->url(array('module'=>'admin','controller'=>'user', 'action'=>'new'));?>">
	<span class="icon-32-new"> </span> Thêm </a></li>

	<li id="toolbar-edit" class="button"><a class="toolbar"
		onclick="submit('<?php echo $this->url(array('module'=>'admin', 'controller'=>'user', 'action'=>'new'));?>',1);"
		href="#"> <span class="icon-32-edit"> </span> Sửa </a></li>
	<li class="divider"></li>

	<li id="toolbar-trash" class="button"><a class="toolbar"
		onclick="submit('<?php echo $this->url(array('module'=>'admin', 'controller'=>'user', 'action'=>'delete'));?>',0)"
		href="#"> <span class="icon-32-trash"> </span> Thùng rác </a></li>

</ul>
<div class="clr"></div>
</div>
<div class="pagetitle icon-48-article">
<h2>Quản lý thành viên quản trị</h2>
</div>
<div class="clr"></div>
</div>
<div class="b">
<div class="b">
<div class="b"></div>
</div>
</div>
</div>

<!-- Nội dung  -->



<div id="element-box">
<div class="t">
<div class="t">
<div class="t"></div>
</div>
</div>
<div class="m">

<form id="adminForm" name="adminForm" method="post" action="">



<table class="adminlist">
	<thead>
		<tr>
			<th width="1%"><input type="checkbox" onclick="checkAll(this);"
				value="" name="checkall-toggle"></th>
			<th width="30%"><a title="Click to sort by this column" href="">Tên đăng nhập</a></th>	

			<th width="30%">Email</th>
			<th width="10%">Vai trò</th>
			<th width="10%">Id</th>

		</tr>
	</thead>
	<tfoot>
		<tr>
			<td colspan="15">
				<div class="container">
					<?php echo $this->paginationControl($this->pages,'Sliding','partials/pagination_control.phtml');?>
				</div>
			</td>
		</tr>
	</tfoot>
	<tbody>
	
	<?php
	$index = 0;	
	foreach ($this->pages as $user):?>
		<tr class="row<?php echo ($index%2==0) ? '0':'1'; ?>">
			<td class="center"><input type="checkbox"
				title="Đánh dấu dòng <?php echo $index;?>"
				onclick="isChecked(this.checked);" value="<?php echo $user['id']; ?>"
				name="cid[]" id="cb<?php echo $index; ?>" /></td>
			<td><a
				href="<?php echo $this->url(array('module'=>'admin', 'controller'=>'user', 'action'=>'new', 'id'=> $user['id']),'default',true);?>">
				<?php echo $user['username'];?></a></td>		

			<td class="center"><?php echo $user['email'];?></td>
			<td class="center"><?php echo $user['role'];?></td>
			<td class="center"><?php echo $user['id'];?></td>
		</tr>
		<?php
		$index++;
		endforeach;?>
		
	</tbody>
</table>

<div>
<input type="hidden" value="0" name="boxchecked">
<div class="clr"></div>
</div>
</form>



</div>
<div class="b">
<div class="b">
<div class="b"></div>
</div>
</div>
</div>
