<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/template.css')
->prependStylesheet($this->baseUrl().'/css/rounded.css');
echo $this->headMeta()->appendHttpEquiv('content-type', 'text/html; charset=utf-8');
?>

<div class="login" id="element-box">
<div class="t">
<div class="t">
<div class="t"></div>
</div>
</div>
<div class="m wbg">
<h1>Đăng nhập trang quản trị</h1>

<div id="section-box">
<div class="t">
<div class="t">
<div class="t"></div>
</div>
</div>
<div class="m">
<form id="form-login" method="post" action="<?php echo $this->url(array('action'=>'login'));?>">
<fieldset class="loginform"><label for="mod-login-username"
	id="mod-login-username-lbl">Tên người dùng</label> <input type="text"
	size="30" class="inputbox" id="mod-login-username" name="username"> <label
	for="mod-login-password" id="mod-login-password-lbl">Mật khẩu</label> <input
	type="password" size="30" class="inputbox" id="mod-login-password"
	name="passwd">
<div class="button-holder">
<div class="button1">
<div class="next"><a
	onclick="document.getElementById('form-login').submit();" href="#">
Đăng nhập</a></div>
</div>
</div>

<div class="clr"></div>
<input type="submit" value="Log in" class="hidebtn"> <input
	type="hidden" value="com_login" name="option"> <input type="hidden"
	value="login" name="task"> <input type="hidden" value="aW5kZXgucGhw"
	name="return"> <input type="hidden" value="1"
	name="70e594ad616cbcee1c4e9cfb78fba450"></fieldset>
</form>
<div class="clr"></div>
</div>
<div class="b">
<div class="b">
<div class="b"></div>
</div>
</div>
</div>


<div id="lock"></div>
<div class="clr"></div>
</div>
<div class="b">
<div class="b">
<div class="b"></div>
</div>
</div>
</div>
