<div id="box_hot_news" class="w980 left">
    <div class="box_news_670 w670 left">
        <div class="left img_362x272">
            <a href="#" title="news sport">
                <img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_362x272.jpg" alt="" />
                <span class="btn_xemvideo">Xem Video</span>
            </a>
        </div>
        <div class="content_news_670 w290 right">
            <div class="main_ct_news">
                <h1><a href="#">Fabregas tỏa sáng đưa Barca vào chung kết Cup Nhà vua</a></h1>
                <p>Với tỷ số 2-0 trong trận bán kết lượt về, Barca vào chung kết bằng chiến thắng chung cuộc 3-1. Thày trò HLV Pep Guardiola sẽ gặp Bilbao trong trận tranh chức vô địch ngày 25/5 tại Madrid.</p>
                <p>
                    <span class="txt_gray">06:40 | 09/02/2012 <span class="icon_portal_thethao icon_commend">&nbsp;</span> 32</span></p>
            </div>
            <ul>
                <li><a href="#" class="txt_black_hover_blue">6 ứng viên sáng giá cho vị trí HLV tuyển Anh </a></li>
                <li><a href="#" class="txt_black_hover_blue">Yaya Toure tái hiện siêu phẩm đá phạt  </a></li>
                <li class="end"><a href="#" class="txt_black_hover_blue">Yaya Toure tái hiện siêu phẩm  Yaya Toure tái hiện siêu phẩm  </a></li>
            </ul>
        </div>
    </div>

    <div class="box_news_300 w300 right">
        <div class="title_tab">
            <ul>
                <li><b>Tin tức </b></li>
                <li class="active"><a href="javascript:;" rel="tab1">Mới nhất</a></li>
                <li><a href="javascript:;" rel="tab2">Đọc nhiều </a></li>
                <li><a href="javascript:;" rel="tab3">Bình luận nhiều</a></li>
            </ul>
        </div>
        <div class="content_news">
            <div class="content_tab tab1" style="display:block;">
                <div class="w280 left txt_news">
                    <div class="right w150">
                        <p><a href="#" class="txt_black_hover_blue">Tương lai của Suarez ở Liverpool “lung lay” dữ dội</a></p>
                        <span class="txt_gray">06:40 | 09/02/2012 <span class="icon_portal_thethao icon_commend">&nbsp;</span> 32</span>
                    </div>
                    <div class="img_155x116 left">
                        <a href="#" title="news"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_123x93.jpg" alt="" /></a>
                    </div>
                </div>
                <ul class="list_dot_3x3">
                    <li><h2><a href="#" class="txt_black_hover_blue">6 ứng viên sáng giá cho vị trí HLV tuyển Anh </a></h2></li>
                    <li><h2><a href="#" class="txt_black_hover_blue">Yaya Toure tái hiện siêu phẩm đá phạt của Roberto Carlos </a></h2></li>
                    <li><h2><a href="#" class="txt_black_hover_blue">6 ứng viên sáng giá cho vị trí HLV tuyển Anh </a></h2></li>
                    <li><h2><a href="#" class="txt_black_hover_blue">Yaya Toure tái hiện siêu phẩm đá phạt của Roberto Carlos </a></h2></li>
                    <li><h2><a href="#" class="txt_black_hover_blue">6 ứng viên sáng giá cho vị trí HLV tuyển Anh </a></h2></li>
                    <li><h2><a href="#" class="txt_black_hover_blue">Yaya Toure tái hiện siêu phẩm đá phạt của Roberto Carlos </a></h2></li>
                </ul>
            </div>
            <div class="content_tab tab2">
                <div class="w280 left txt_news">
                    <div class="right w150">
                        <p><a href="#" class="txt_black_hover_blue">2 Tương lai của Suarez ở Liverpool “lung lay” dữ dội</a></p>
                        <span class="txt_gray">06:40 | 09/02/2012 <span class="icon_portal_thethao icon_commend">&nbsp;</span> 32</span>
                    </div>
                    <div class="img_155x116 left">
                        <a href="#" title="news"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_123x93.jpg" alt="" /></a>
                    </div>
                </div>
                <ul class="list_dot_3x3">
                    <li><h2><a href="#" class="txt_black_hover_blue">6 ứng viên sáng giá cho vị trí HLV tuyển Anh </a></h2></li>
                    <li><h2><a href="#" class="txt_black_hover_blue">Yaya Toure tái hiện siêu phẩm đá phạt của Roberto Carlos </a></h2></li>
                    <li><h2><a href="#" class="txt_black_hover_blue">6 ứng viên sáng giá cho vị trí HLV tuyển Anh </a></h2></li>
                    <li><h2><a href="#" class="txt_black_hover_blue">Yaya Toure tái hiện siêu phẩm đá phạt của Roberto Carlos </a></h2></li>
                    <li><h2><a href="#" class="txt_black_hover_blue">6 ứng viên sáng giá cho vị trí HLV tuyển Anh </a></h2></li>
                    <li><h2><a href="#" class="txt_black_hover_blue">Yaya Toure tái hiện siêu phẩm đá phạt của Roberto Carlos </a></h2></li>
                </ul>
            </div>
            <div class="content_tab tab3">
                <div class="w280 left txt_news">
                    <div class="right w150">
                        <p><a href="#" class="txt_black_hover_blue">3 Tương lai của Suarez ở Liverpool “lung lay” dữ dội</a></p>
                        <span class="txt_gray">06:40 | 09/02/2012 <span class="icon_portal_thethao icon_commend">&nbsp;</span> 32</span>
                    </div>
                    <div class="img_155x116 left">
                        <a href="#" title="news"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_123x93.jpg" alt="" /></a>
                    </div>
                </div>
                <ul class="list_dot_3x3">
                    <li><h2><a href="#" class="txt_black_hover_blue">6 ứng viên sáng giá cho vị trí HLV tuyển Anh </a></h2></li>
                    <li><h2><a href="#" class="txt_black_hover_blue">Yaya Toure tái hiện siêu phẩm đá phạt của Roberto Carlos </a></h2></li>
                    <li><h2><a href="#" class="txt_black_hover_blue">6 ứng viên sáng giá cho vị trí HLV tuyển Anh </a></h2></li>
                    <li><h2><a href="#" class="txt_black_hover_blue">Yaya Toure tái hiện siêu phẩm đá phạt của Roberto Carlos </a></h2></li>
                    <li><h2><a href="#" class="txt_black_hover_blue">6 ứng viên sáng giá cho vị trí HLV tuyển Anh </a></h2></li>
                    <li><h2><a href="#" class="txt_black_hover_blue">Yaya Toure tái hiện siêu phẩm đá phạt của Roberto Carlos </a></h2></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- InstanceEndEditable -->
<div class="w980 left">
    <div id="col_left" class="w670 left"> 
        <!-- InstanceBeginEditable name="Content col left" -->
        <div id="box_video_hot"  class=" box_col_670 box_width_common left">
            <div class="main_content_box">
                <div class="tab_video title_tab">
                    <ul>
                        <li class="active"><a href="javascript:;" rel="tab1">Video Clip mới</a></li>
                        <li><a href="javascript:;" rel="tab2">Ảnh Mới</a></li>
                    </ul>
                </div>
                <div class="content_tab tab1" style="display:block;">
                    <div class="content_box_video">
                        <div id="slides_video">
                            <div class="slides_container">
                                <ul>
                                    <li>
                                        <div class="block_image_thumb">
                                            <a href="#" title="video name"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_155x116.jpg" alt="" />
                                                <span class="icon_play">&nbsp;</span>                                                    </a>                                                </div>
                                        <h2>
                                            <a href="#" class="">Suarez gây sốc với hành động bạo lực trong ngày trở lại </a>                                     </h2>
                                        <p class="txt_gray txt_11">lượt xem:530</p>
                                    </li>
                                    <li>
                                        <div class="block_image_thumb">
                                            <a href="#" title="video name"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_155x116.jpg" alt="" />
                                                <span class="icon_play">&nbsp;</span>                                                    </a>                                                </div>
                                        <h2>
                                            <a href="#" class="">Suarez gây sốc với hành động bạo lực trong ngày trở lại </a>                                     </h2>
                                        <p class="txt_gray txt_11">lượt xem:530</p>
                                    </li>
                                    <li>
                                        <div class="block_image_thumb">
                                            <a href="#" title="video name"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_155x116.jpg" alt="" />
                                                <span class="icon_play">&nbsp;</span>                                                    </a>                                                </div>
                                        <h2>
                                            <a href="#" class="">Suarez gây sốc với hành động bạo lực trong ngày trở lại </a>                                     </h2>
                                        <p class="txt_gray txt_11">lượt xem:530</p>
                                    </li>
                                    <li>
                                        <div class="block_image_thumb">
                                            <a href="#" title="video name"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_155x116.jpg" alt="" />
                                                <span class="icon_play">&nbsp;</span>                                                    </a>                                                </div>
                                        <h2>
                                            <a href="#" class="">Suarez gây sốc với hành động bạo lực trong ngày trở lại </a>                                     </h2>
                                        <p class="txt_gray txt_11">lượt xem:530</p>
                                    </li>
                                </ul>
                                <ul>
                                    <li>
                                        <div class="block_image_thumb">
                                            <a href="#" title="video name"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_155x116.jpg" alt="" />
                                                <span class="icon_play">&nbsp;</span>                                                    </a>                                                </div>
                                        <h2>
                                            <a href="#" class="">Suarez gây sốc với hành động bạo lực trong ngày trở lại </a>                                     </h2>
                                        <p class="txt_gray txt_11">lượt xem:530</p>
                                    </li>
                                    <li>
                                        <div class="block_image_thumb">
                                            <a href="#" title="video name"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_155x116.jpg" alt="" />
                                                <span class="icon_play">&nbsp;</span>                                                    </a>                                                </div>
                                        <h2>
                                            <a href="#" class="">Suarez gây sốc với hành động bạo lực trong ngày trở lại </a>                                     </h2>
                                        <p class="txt_gray txt_11">lượt xem:530</p>
                                    </li>
                                    <li>
                                        <div class="block_image_thumb">
                                            <a href="#" title="video name"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_155x116.jpg" alt="" />
                                                <span class="icon_play">&nbsp;</span>                                                    </a>                                                </div>
                                        <h2>
                                            <a href="#" class="">Suarez gây sốc với hành động bạo lực trong ngày trở lại </a>                                     </h2>
                                        <p class="txt_gray txt_11">lượt xem:530</p>
                                    </li>
                                    <li>
                                        <div class="block_image_thumb">
                                            <a href="#" title="video name"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_155x116.jpg" alt="" />
                                                <span class="icon_play">&nbsp;</span>                                                    </a>                                                </div>
                                        <h2>
                                            <a href="#" class="">Suarez gây sốc với hành động bạo lực trong ngày trở lại </a>                                     </h2>
                                        <p class="txt_gray txt_11">lượt xem:530</p>
                                    </li>
                                </ul>
                                <ul>
                                    <li>
                                        <div class="block_image_thumb">
                                            <a href="#" title="video name"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_155x116.jpg" alt="" />
                                                <span class="icon_play">&nbsp;</span>                                                    </a>                                                </div>
                                        <h2>
                                            <a href="#" class="">Suarez gây sốc với hành động bạo lực trong ngày trở lại </a>                                     </h2>
                                        <p class="txt_gray txt_11">lượt xem:530</p>
                                    </li>
                                    <li>
                                        <div class="block_image_thumb">
                                            <a href="#" title="video name"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_155x116.jpg" alt="" />
                                                <span class="icon_play">&nbsp;</span>                                                    </a>                                                </div>
                                        <h2>
                                            <a href="#" class="">Suarez gây sốc với hành động bạo lực trong ngày trở lại </a>                                     </h2>
                                        <p class="txt_gray txt_11">lượt xem:530</p>
                                    </li>
                                    <li>
                                        <div class="block_image_thumb">
                                            <a href="#" title="video name"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_155x116.jpg" alt="" />
                                                <span class="icon_play">&nbsp;</span>                                                    </a>                                                </div>
                                        <h2>
                                            <a href="#" class="">Suarez gây sốc với hành động bạo lực trong ngày trở lại </a>                                     </h2>
                                        <p class="txt_gray txt_11">lượt xem:530</p>
                                    </li>
                                    <li>
                                        <div class="block_image_thumb">
                                            <a href="#" title="video name"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_155x116.jpg" alt="" />
                                                <span class="icon_play">&nbsp;</span>                                                    </a>                                                </div>
                                        <h2>
                                            <a href="#" class="">Suarez gây sốc với hành động bạo lực trong ngày trở lại </a>                                     </h2>
                                        <p class="txt_gray txt_11">lượt xem:530</p>
                                    </li>
                                </ul>
                                <ul>
                                    <li>
                                        <div class="block_image_thumb">
                                            <a href="#" title="video name"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_155x116.jpg" alt="" />
                                                <span class="icon_play">&nbsp;</span>                                                    </a>                                                </div>
                                        <h2>
                                            <a href="#" class="">Suarez gây sốc với hành động bạo lực trong ngày trở lại </a>                                     </h2>
                                        <p class="txt_gray txt_11">lượt xem:530</p>
                                    </li>
                                    <li>
                                        <div class="block_image_thumb">
                                            <a href="#" title="video name"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_155x116.jpg" alt="" />
                                                <span class="icon_play">&nbsp;</span>                                                    </a>                                                </div>
                                        <h2>
                                            <a href="#" class="">Suarez gây sốc với hành động bạo lực trong ngày trở lại </a>                                     </h2>
                                        <p class="txt_gray txt_11">lượt xem:530</p>
                                    </li>
                                    <li>
                                        <div class="block_image_thumb">
                                            <a href="#" title="video name"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_155x116.jpg" alt="" />
                                                <span class="icon_play">&nbsp;</span>                                                    </a>                                                </div>
                                        <h2>
                                            <a href="#" class="">Suarez gây sốc với hành động bạo lực trong ngày trở lại </a>                                     </h2>
                                        <p class="txt_gray txt_11">lượt xem:530</p>
                                    </li>
                                    <li>
                                        <div class="block_image_thumb">
                                            <a href="#" title="video name"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_155x116.jpg" alt="" />
                                                <span class="icon_play">&nbsp;</span>                                                    </a>                                                </div>
                                        <h2>
                                            <a href="#" class="">Suarez gây sốc với hành động bạo lực trong ngày trở lại </a>                                     </h2>
                                        <p class="txt_gray txt_11">lượt xem:530</p>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="content_tab tab2">
                    <div class="content_box_video">
                        <div id="slides_photo">
                            <div class="slides_container">
                                <ul>
                                    <li>
                                        <div class="block_image_thumb">
                                            <a href="#" title="video name"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_155x116.jpg" alt="" />
                                                <span class="icon_photo">&nbsp;</span>                                                    </a>                                                </div>
                                        <h2>
                                            <a href="#" class="">Suarez gây sốc với hành động bạo lực trong ngày trở lại </a>                                     </h2>
                                        <p class="txt_gray txt_11">lượt xem:530</p>
                                    </li>
                                    <li>
                                        <div class="block_image_thumb">
                                            <a href="#" title="video name"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_155x116.jpg" alt="" />
                                                <span class="icon_photo">&nbsp;</span>                                                    </a>                                                </div>
                                        <h2>
                                            <a href="#" class="">Suarez gây sốc với hành động bạo lực trong ngày trở lại </a>                                     </h2>
                                        <p class="txt_gray txt_11">lượt xem:530</p>
                                    </li>
                                    <li>
                                        <div class="block_image_thumb">
                                            <a href="#" title="video name"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_155x116.jpg" alt="" />
                                                <span class="icon_photo">&nbsp;</span>                                                    </a>                                                </div>
                                        <h2>
                                            <a href="#" class="">Suarez gây sốc với hành động bạo lực trong ngày trở lại </a>                                     </h2>
                                        <p class="txt_gray txt_11">lượt xem:530</p>
                                    </li>
                                    <li>
                                        <div class="block_image_thumb">
                                            <a href="#" title="video name"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_155x116.jpg" alt="" />
                                                <span class="icon_photo">&nbsp;</span>                                                    </a>                                                </div>
                                        <h2>
                                            <a href="#" class="">Suarez gây sốc với hành động bạo lực trong ngày trở lại </a>                                     </h2>
                                        <p class="txt_gray txt_11">lượt xem:530</p>
                                    </li>
                                </ul>
                                <ul>
                                    <li>
                                        <div class="block_image_thumb">
                                            <a href="#" title="video name"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_155x116.jpg" alt="" />
                                                <span class="icon_photo">&nbsp;</span>                                                    </a>                                                </div>
                                        <h2>
                                            <a href="#" class="">Suarez gây sốc với hành động bạo lực trong ngày trở lại </a>                                     </h2>
                                        <p class="txt_gray txt_11">lượt xem:530</p>
                                    </li>
                                    <li>
                                        <div class="block_image_thumb">
                                            <a href="#" title="video name"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_155x116.jpg" alt="" />
                                                <span class="icon_photo">&nbsp;</span>                                                    </a>                                                </div>
                                        <h2>
                                            <a href="#" class="">Suarez gây sốc với hành động bạo lực trong ngày trở lại </a>                                     </h2>
                                        <p class="txt_gray txt_11">lượt xem:530</p>
                                    </li>
                                    <li>
                                        <div class="block_image_thumb">
                                            <a href="#" title="video name"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_155x116.jpg" alt="" />
                                                <span class="icon_photo">&nbsp;</span>                                                    </a>                                                </div>
                                        <h2>
                                            <a href="#" class="">Suarez gây sốc với hành động bạo lực trong ngày trở lại </a>                                     </h2>
                                        <p class="txt_gray txt_11">lượt xem:530</p>
                                    </li>
                                    <li>
                                        <div class="block_image_thumb">
                                            <a href="#" title="video name"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_155x116.jpg" alt="" />
                                                <span class="icon_photo">&nbsp;</span>                                                    </a>                                                </div>
                                        <h2>
                                            <a href="#" class="">Suarez gây sốc với hành động bạo lực trong ngày trở lại </a>                                     </h2>
                                        <p class="txt_gray txt_11">lượt xem:530</p>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="cate_bongdaqt" class="box_width_common">
            <div class="title_cate">
                <p class="left">BÓNG ĐÁ QUỐC TẾ</p>
            </div>
            <div class="content_cate">
                <div class="block_chuyennhuong box_width_common left">
                    <div class="title_block">
                        <div class="txt_title_left_block"><h3><a href="#" class="txt_black_hover_blue">Tin tức chuyển nhượng</a></h3></div>
                        <div class="txt_view_more"><a class="txt_gray" href="#">Xem thêm</a> <span class="icon_portal_thethao icon_view_more">&nbsp;</span></div>	
                        <div class="clear">&nbsp;</div>  
                    </div>
                    <div class="content_block">
                        <div class="main_content_block">
                            <div class="w320 left">
                                <div class="news_left">
                                    <a href="#" title="news name"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_123x93.jpg" alt="" /></a>
                                    <p><a href="#" class="txt_black_hover_blue"><b>Tevez tố bị HLV Mancini đối xử 'như chó' </b></a></p>
                                    <p class="txt_gray txt_11">06:40 | 09/02/2012 <span class="icon_portal_thethao icon_commend">&nbsp;</span> 32</p>
                                    <p>Tiền đạo nổi loạn người Argentina có vẻ không màng tới động thái nối Tiền đạo nổi loạn người Argentina có vẻ không màng tới động thái nố lại hòa khí của HLV Mancini.</p>
                                </div>
                            </div>
                            <div class="w320 right">
                                <div class="news_right">
                                    <div class="title_news">
                                        <a href="#" title="news name"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_73x54.jpg" alt="" /></a>
                                        <p><a href="#" class="txt_black_hover_blue"><b>Tevez tố bị HLV Mancini đối xử 'như chó' </b></a></p>
                                    </div>
                                    <ul class="list_dot_3x3">
                                        <li><a href="#"><b>Whitney Houston háịch sử thể thao'</b></a></li>
                                        <li><a href="#"><b>Hoàng Quý Phước tìm chuẩn A trên đất Mỹ  trên đất Mỹ  trên đất Mỹ</b></a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="clear">&nbsp;</div>
                        </div>
                    </div>

                </div>
                <div class="block_vdqg box_width_common">
                    <div class="title_block">
                        <div class="txt_title_left_block"><h3><a href="#" class="txt_black_hover_blue">Các giải vô địch quốc gia</a></h3></div>
                        <ul class="list_qg">
                            <li class="active"><a href="#">Ngoại hạng Anh</a> </li>
                            <li><a href="#">Italia</a></li>
                            <li><a href="#">TBN</a> </li>
                            <li><a href="#">Đức</a></li>
                            <li class="end"><a href="#">Brasil</a></li>
                        </ul>
                        <div class="txt_view_more"><a class="txt_gray" href="#">Xem thêm</a> <span class="icon_portal_thethao icon_view_more">&nbsp;</span></div>	
                        <div class="clear">&nbsp;</div>  
                    </div>
                    <div class="content_block">
                        <div class="main_content_block">
                            <div class="w320 left">
                                <div class="news_left">
                                    <ul class="list_news">
                                        <li><a href="#" title="news name"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_155x116.jpg" alt="" /></a>
                                            <div class="decs">
                                                <p><a href="#" class="txt_black_hover_blue"><b>Tevez tố bị HLV Mancini đối xử 'như chó' </b></a></p>
                                                <p class="txt_gray txt_11">06:40 | 09/02/2012 <span class="icon_portal_thethao icon_commend">&nbsp;</span> 32</p>
                                            </div>
                                        </li>
                                        <li class="end"><a href="#" title="news name"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_155x116.jpg" alt="" /></a>
                                            <div class="decs">
                                                <p><a href="#" class="txt_black_hover_blue"><b>Tevez tố bị HLV Mancini đối xử 'như chó'  Tevez tố bị HLV Mancin</b></a></p>
                                                <p class="txt_gray txt_11">06:40 | 09/02/2012 <span class="icon_portal_thethao icon_commend">&nbsp;</span> 32</p>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="w320 right">
                                <div class="news_right">
                                    <ul class="list_dot_3x3">
                                        <li>
                                            <div class="box_width_common dot_bottom">
                                                <p><a href="#" class="txt_black_hover_blue"><b>Whitney Houston háịch sử thể thao'</b></a></p>
                                                <p>Thi đấu rời rạc và thiếu quyết tâm, Arsenal đã phải nhận trận thua 0-2 bẽ bàng trên sân của Sunderland ở vòng 5 Cup FA tối qua.</p>
                                            </div>
                                        </li>
                                        <li>
                                            <div class="box_width_common dot_bottom">
                                                <p><a href="#" class="txt_black_hover_blue"><b>Whitney Houston háịch sử thể thao'</b></a></p>
                                                <p>Thi đấu rời rạc và thiếu quyết tâm, Arsenal đã phải nhận trận thua 0-2 bẽ bàng trên sân của Sunderland ở vòng 5 Cup FA tối qua.</p>
                                            </div>
                                        </li>
                                        <li>
                                            <div class="box_width_common dot_bottom">
                                                <p><a href="#" class="txt_black_hover_blue"><b>Whitney Houston háịch sử thể thao'</b></a></p>
                                                <p>Thi đấu rời rạc và thiếu quyết tâm, Arsenal đã phải nhận trận thua 0-2 bẽ bàng trên sân của Sunderland ở vòng 5 Cup FA tối qua.</p>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="clear">&nbsp;</div>
                        </div>
                    </div>

                </div>
                <div class="block_champoinsleague box_width_common left">
                    <div class="title_block">
                        <div class="txt_title_left_block"><h3><a href="#" class="txt_black_hover_blue">Champions League </a></h3></div>
                        <div class="txt_view_more"><a class="txt_gray" href="#">Xem thêm</a> <span class="icon_portal_thethao icon_view_more">&nbsp;</span></div>	
                        <div class="clear">&nbsp;</div>  
                    </div>
                    <div class="content_block">
                        <div class="main_content_block">
                            <div class="w320 left">
                                <div class="news_left">
                                    <a href="#" title="news name"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_123x93.jpg" alt="" /></a>
                                    <p><a href="#" class="txt_black_hover_blue"><b>Tevez tố bị HLV Mancini đối xử 'như chó' </b></a></p>
                                    <p class="txt_gray txt_11">06:40 | 09/02/2012 <span class="icon_portal_thethao icon_commend">&nbsp;</span> 32</p>
                                    <p>Tiền đạo nổi loạn người Argentina có vẻ không màng tới động thái nối Tiền đạo nổi loạn người Argentina có vẻ không màng tới động thái nố lại hòa khí của HLV Mancini.</p>
                                </div>
                            </div>
                            <div class="w320 right">
                                <div class="news_right">
                                    <div class="title_news">
                                        <a href="#" title="news name"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_73x54.jpg" alt="" /></a>
                                        <p><a href="#" class="txt_black_hover_blue"><b>Tevez tố bị HLV Mancini đối xử 'như chó' </b></a></p>
                                    </div>
                                    <ul class="list_dot_3x3">
                                        <li><a href="#"><b>Whitney Houston háịch sử thể thao'</b></a></li>
                                        <li><a href="#"><b>Hoàng Quý Phước tìm chuẩn A trên đất Mỹ  trên đất Mỹ  trên đất Mỹ</b></a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="clear">&nbsp;</div>
                        </div>
                    </div>

                </div>
                <div class="clear">&nbsp;</div>
            </div>
        </div>
        <div class="banner_mid w670 left">
            <a href="#" title="ads"><img src="<?php echo TEMPLATE_URL ?>/default/images/ads/ads_475x60.jpg" alt="" /></a>
        </div>
        <div id="cate_euro" class="box_width_common football">
            <div class="title_cate">
                <p class="left">EURO 2012</p>
                <div class="txt_view_more"><a class="txt_gray" href="#">Xem thêm</a> <span class="icon_portal_thethao icon_view_more">&nbsp;</span></div>	
            </div>
            <div class="content_cate">
                <div class="block_vdqg box_width_common left">
                    <div class="content_block">
                        <div class="w320 left">
                            <div class="news_left">
                                <ul class="list_news">
                                    <li><a href="#" title="news name"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_155x116.jpg" alt="" /></a>
                                        <div class="decs">
                                            <p><a href="#" class="txt_black_hover_blue"><b>Tevez tố bị HLV Mancini đối xử 'như chó' </b></a></p>
                                            <p class="txt_gray txt_11">06:40 | 09/02/2012 <span class="icon_portal_thethao icon_commend">&nbsp;</span> 32</p>
                                        </div>
                                    </li>
                                    <li class="end"><a href="#" title="news name"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_155x116.jpg" alt="" /></a>
                                        <div class="decs">
                                            <p><a href="#" class="txt_black_hover_blue"><b>Tevez tố bị HLV Mancini đối xử 'như chó'  Tevez tố bị HLV Mancin</b></a></p>
                                            <p class="txt_gray txt_11">06:40 | 09/02/2012 <span class="icon_portal_thethao icon_commend">&nbsp;</span> 32</p>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="w320 right">
                            <div class="news_right">
                                <ul class="list_dot_3x3">
                                    <li>
                                        <div class="box_width_common dot_bottom">
                                            <p><a href="#" class="txt_black_hover_blue"><b>Whitney Houston háịch sử thể thao'</b></a></p>
                                            <p>Thi đấu rời rạc và thiếu quyết tâm, Arsenal đã phải nhận trận thua 0-2 bẽ bàng trên sân của Sunderland ở vòng 5 Cup FA tối qua.</p>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="box_width_common dot_bottom">
                                            <p><a href="#" class="txt_black_hover_blue"><b>Whitney Houston háịch sử thể thao'</b></a></p>
                                            <p>Thi đấu rời rạc và thiếu quyết tâm, Arsenal đã phải nhận trận thua 0-2 bẽ bàng trên sân của Sunderland ở vòng 5 Cup FA tối qua.</p>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="box_width_common dot_bottom">
                                            <p><a href="#" class="txt_black_hover_blue"><b>Whitney Houston háịch sử thể thao'</b></a></p>
                                            <p>Thi đấu rời rạc và thiếu quyết tâm, Arsenal đã phải nhận trận thua 0-2 bẽ bàng trên sân của Sunderland ở vòng 5 Cup FA tối qua.</p>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="clear">&nbsp;</div>

                    </div>

                </div>
                <div class="clear">&nbsp;</div>
            </div>
        </div>
        <div class="w670 left">

            <div class="w330 left">
                <div id="cate_bdtn" class="box_width_common football">
                    <div class="title_cate">
                        <p class="left">BÓNG ĐÁ TRONG NƯỚC</p>
                        <div class="txt_view_more"><a class="txt_gray" href="#">Xem thêm</a> <span class="icon_portal_thethao icon_view_more">&nbsp;</span></div>	
                    </div>
                    <div class="content_cate">
                        <div class="w310 left">
                            <div class="news_images dot_bottom">
                                <a href="#" title="news name"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_123x93.jpg" alt="" /></a>
                                <p><a href="#" class="txt_black_hover_blue"><b>Tevez tố bị HLV Mancini đối xử 'như chó' </b></a></p>
                                <p class="txt_gray txt_11">06:40 | 09/02/2012 <span class="icon_portal_thethao icon_commend">&nbsp;</span> 32</p>
                                <p>Tiền đạo nổi loạn người Argentina có vẻ không màng tới động thái nối Tiền đạo nổi loạn người Argentina có vẻ không màng tới động thái nố lại hòa khí của HLV Mancini.</p>
                            </div>
                            <div class="news_images">
                                <a href="#" title="news name"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_123x93.jpg" alt="" /></a>
                                <p><a href="#" class="txt_black_hover_blue"><b>Tevez tố bị HLV Mancini đối xử 'như chó' </b></a></p>
                                <p class="txt_gray txt_11">06:40 | 09/02/2012 <span class="icon_portal_thethao icon_commend">&nbsp;</span> 32</p>
                                <p>Tiền đạo nổi loạn người Argentina có vẻ không màng tới động thái nối Tiền đạo nổi loạn người Argentina có vẻ không màng tới động thái nố lại hòa khí của HLV Mancini.</p>
                            </div>
                        </div>
                        <div class="w310 left">
                            <div class="news_noimages">
                                <ul class="list_dot_3x3">
                                    <li>
                                        <div class="box_width_common">
                                            <p><a href="#" class="txt_black_hover_blue"><b>Whitney Houston háịch sử thể thao'</b></a></p>
                                            <p>Thi đấu rời rạc và thiếu quyết tâm, Arsenal đã phải nhận trận thua 0-2 bẽ bàng trên sân của Sunderland ở vòng 5 Cup FA tối qua.</p>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="box_width_common">
                                            <p><a href="#" class="txt_black_hover_blue"><b>Whitney Houston háịch sử thể thao'</b></a></p>
                                            <p>Thi đấu rời rạc và thiếu quyết tâm, Arsenal đã phải nhận trận thua 0-2 bẽ bàng trên sân của Sunderland ở vòng 5 Cup FA tối qua.</p>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="box_width_common">
                                            <p><a href="#" class="txt_black_hover_blue"><b>Whitney Houston háịch sử thể thao'</b></a></p>
                                            <p>Thi đấu rời rạc và thiếu quyết tâm, Arsenal đã phải nhận trận thua 0-2 bẽ bàng trên sân của Sunderland ở vòng 5 Cup FA tối qua.</p>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="clear">&nbsp;</div>
                    </div>
                </div>
            </div>
            <div class="w330 right">
                <div id="cate_tennis" class="box_width_common football">
                    <div class="title_cate">
                        <p class="left">TENNIS</p>
                        <div class="txt_view_more"><a class="txt_gray" href="#">Xem thêm</a> <span class="icon_portal_thethao icon_view_more">&nbsp;</span></div>	
                    </div>
                    <div class="content_cate">
                        <div class="w310 left">
                            <div class="news_images">
                                <a href="#" title="news name"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_123x93.jpg" alt="" /></a>
                                <p><a href="#" class="txt_black_hover_blue"><b>Tevez tố bị HLV Mancini đối xử 'như chó' </b></a></p>
                                <p class="txt_gray txt_11">06:40 | 09/02/2012 <span class="icon_portal_thethao icon_commend">&nbsp;</span> 32</p>
                                <p>Tiền đạo nổi loạn người Argentina có vẻ không màng tới động thái nối Tiền đạo nổi loạn người Argentina có vẻ không màng tới động thái nố lại hòa khí của HLV Mancini.</p>
                            </div>
                        </div>
                        <div class="w310 left">
                            <div class="news_noimages">
                                <ul class="list_dot_3x3">
                                    <li>
                                        <div class="box_width_common">
                                            <p><a href="#" class="txt_black_hover_blue"><b>Whitney Houston háịch sử thể thao'</b></a></p>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="box_width_common">
                                            <p><a href="#" class="txt_black_hover_blue"><b>Nadal ngược dòng giúp Tây Ban Nha lên ngôi Davis Cup </b></a></p>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="box_width_common">
                                            <p><a href="#" class="txt_black_hover_blue"><b>Đả bại Nadal, Djokovic bảo vệ ngôi vương ở Australia Mở rộng</b></a></p>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="clear">&nbsp;</div>
                    </div>
                </div>
                <div id="cate_thethaokhac" class="box_width_common football">
                    <div class="title_cate">
                        <p class="left">CÁC MÔN THỂ THAO KHÁC</p>
                        <div class="txt_view_more"><a class="txt_gray" href="#">Xem thêm</a> <span class="icon_portal_thethao icon_view_more">&nbsp;</span></div>	
                    </div>
                    <div class="content_cate">
                        <div class="w310 left">
                            <div class="news_images">
                                <a href="#" title="news name"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_123x93.jpg" alt="" /></a>
                                <p><a href="#" class="txt_black_hover_blue"><b>Tevez tố bị HLV Mancini đối xử 'như chó' </b></a></p>
                                <p class="txt_gray txt_11">06:40 | 09/02/2012 <span class="icon_portal_thethao icon_commend">&nbsp;</span> 32</p>
                                <p>Tiền đạo nổi loạn người Argentina có vẻ không màng tới động thái nối Tiền đạo nổi loạn người Argentina có vẻ không màng tới động thái nố lại hòa khí của HLV Mancini.</p>
                            </div>
                        </div>
                        <div class="w310 left">
                            <div class="news_noimages">
                                <ul class="list_dot_3x3">
                                    <li>
                                        <div class="box_width_common">
                                            <p><a href="#" class="txt_black_hover_blue"><b>Whitney Houston háịch sử thể thao'</b></a></p>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="box_width_common">
                                            <p><a href="#" class="txt_black_hover_blue"><b>Nadal ngược dòng giúp Tây Ban Nha lên ngôi Davis Cup </b></a></p>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="box_width_common">
                                            <p><a href="#" class="txt_black_hover_blue"><b>Đả bại Nadal, Djokovic bảo vệ ngôi vương ở Australia Mở rộng</b></a></p>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="clear">&nbsp;</div>
                    </div>
                </div>
            </div>
        </div>

        <!-- InstanceEndEditable --> 
    </div>
    <div id="col_right" class="w300 right"> 
        <!-- InstanceBeginEditable name="Content col Right" -->
        <div class="banner_300x250 left w300">
            <a href="#" title="ads"><img src="<?php echo TEMPLATE_URL ?>/default/images/ads/ads_300x250.jpg" alt="" /></a>
        </div>
        <div id="box_bxh_bongda" class="box_col_300 box_width_common left">
            <div class="txt_title_box">Bảng xếp hạng bóng đá châu Âu 2011 - 2012</div>
            <div class="title_tab">
                <ul>
                    <li class="start active"><a href="javascript:;" rel="tab1">England</a></li>
                    <li><a href="javascript:;" rel="tab2"> Italy </a></li>
                    <li><a href="javascript:;" rel="tab3">Germany </a></li>
                    <li><a href="javascript:;" rel="tab4"> Spain</a></li>
                </ul>
            </div>
            <div class="content_news">
                <div class="content_tab tab1"  style="display:block;">
                    <table class="tb_bxh">
                        <tr class="top">
                            <td class="w150">Team</td>
                            <td class="w20">W</td>
                            <td class="w20">D</td>
                            <td class="w20">L</td>
                            <td class="w60">Pts</td>
                        </tr>
                        <tr class="top2">
                            <td class="w150"><a href="#" class="txt_black_hover_blue">Manchester United</a></td>
                            <td class="w20">17</td>
                            <td class="w20">3</td>
                            <td class="w20">4</td>
                            <td class="w60">54</td>
                        </tr>
                        <tr class="top2">
                            <td class="w150"><a href="#" class="txt_black_hover_blue">Manchester United</a></td>
                            <td class="w20">17</td>
                            <td class="w20">3</td>
                            <td class="w20">4</td>
                            <td class="w60">54</td>
                        </tr>
                        <tr class="top2">
                            <td class="w150"><a href="#" class="txt_black_hover_blue">Manchester United</a></td>
                            <td class="w20">17</td>
                            <td class="w20">3</td>
                            <td class="w20">4</td>
                            <td class="w60">54</td>
                        </tr>
                        <tr class="top3">
                            <td class="w150"><a href="#" class="txt_black_hover_blue">Manchester United</a></td>
                            <td class="w20">17</td>
                            <td class="w20">3</td>
                            <td class="w20">4</td>
                            <td class="w60">54</td>
                        </tr>
                        <tr class="top4">
                            <td class="w150"><a href="#" class="txt_black_hover_blue">Manchester United</a></td>
                            <td class="w20">17</td>
                            <td class="w20">3</td>
                            <td class="w20">4</td>
                            <td class="w60">54</td>
                        </tr>
                        <tr>
                            <td class="w150"><a href="#" class="txt_black_hover_blue">Manchester United</a></td>
                            <td class="w20">17</td>
                            <td class="w20">3</td>
                            <td class="w20">4</td>
                            <td class="w60">54</td>
                        </tr>
                        <tr>
                            <td class="w150"><a href="#" class="txt_black_hover_blue">Manchester United</a></td>
                            <td class="w20">17</td>
                            <td class="w20">3</td>
                            <td class="w20">4</td>
                            <td class="w60">54</td>
                        </tr>
                        <tr>
                            <td class="w150"><a href="#" class="txt_black_hover_blue">Manchester United</a></td>
                            <td class="w20">17</td>
                            <td class="w20">3</td>
                            <td class="w20">4</td>
                            <td class="w60">54</td>
                        </tr>
                        <tr>
                            <td class="w150"><a href="#" class="txt_black_hover_blue">Manchester United</a></td>
                            <td class="w20">17</td>
                            <td class="w20">3</td>
                            <td class="w20">4</td>
                            <td class="w60">54</td>
                        </tr>
                        <tr>
                            <td class="w150"><a href="#" class="txt_black_hover_blue">Manchester United</a></td>
                            <td class="w20">17</td>
                            <td class="w20">3</td>
                            <td class="w20">4</td>
                            <td class="w60">54</td>
                        </tr>
                    </table>
                    <div class="txt_view_more"><a href="#" class="txt_gray">Chi tiết bảng xếp hạng</a> <span class="icon_portal_thethao icon_view_more">&nbsp;</span></div>                         
                </div>
                <div class="content_tab tab2">
                    <table class="tb_bxh">
                        <tr class="top">
                            <td class="w150">Team</td>
                            <td class="w20">W</td>
                            <td class="w20">D</td>
                            <td class="w20">L</td>
                            <td class="w60">Pts</td>
                        </tr>
                        <tr class="top2">
                            <td class="w150"><a href="#" class="txt_black_hover_blue">Manchester United</a></td>
                            <td class="w20">17</td>
                            <td class="w20">3</td>
                            <td class="w20">4</td>
                            <td class="w60">54</td>
                        </tr>
                        <tr class="top2">
                            <td class="w150"><a href="#" class="txt_black_hover_blue">Manchester United</a></td>
                            <td class="w20">17</td>
                            <td class="w20">3</td>
                            <td class="w20">4</td>
                            <td class="w60">54</td>
                        </tr>
                        <tr class="top2">
                            <td class="w150"><a href="#" class="txt_black_hover_blue">Manchester United</a></td>
                            <td class="w20">17</td>
                            <td class="w20">3</td>
                            <td class="w20">4</td>
                            <td class="w60">54</td>
                        </tr>
                        <tr class="top3">
                            <td class="w150"><a href="#" class="txt_black_hover_blue">Manchester United</a></td>
                            <td class="w20">17</td>
                            <td class="w20">3</td>
                            <td class="w20">4</td>
                            <td class="w60">54</td>
                        </tr>
                        <tr class="top4">
                            <td class="w150"><a href="#" class="txt_black_hover_blue">Manchester United</a></td>
                            <td class="w20">17</td>
                            <td class="w20">3</td>
                            <td class="w20">4</td>
                            <td class="w60">54</td>
                        </tr>
                        <tr>
                            <td class="w150"><a href="#" class="txt_black_hover_blue">Manchester United</a></td>
                            <td class="w20">17</td>
                            <td class="w20">3</td>
                            <td class="w20">4</td>
                            <td class="w60">54</td>
                        </tr>
                        <tr>
                            <td class="w150"><a href="#" class="txt_black_hover_blue">Manchester United</a></td>
                            <td class="w20">17</td>
                            <td class="w20">3</td>
                            <td class="w20">4</td>
                            <td class="w60">54</td>
                        </tr>
                        <tr>
                            <td class="w150"><a href="#" class="txt_black_hover_blue">Manchester United</a></td>
                            <td class="w20">17</td>
                            <td class="w20">3</td>
                            <td class="w20">4</td>
                            <td class="w60">54</td>
                        </tr>
                        <tr>
                            <td class="w150"><a href="#" class="txt_black_hover_blue">Manchester United</a></td>
                            <td class="w20">17</td>
                            <td class="w20">3</td>
                            <td class="w20">4</td>
                            <td class="w60">54</td>
                        </tr>
                        <tr>
                            <td class="w150"><a href="#" class="txt_black_hover_blue">Manchester United</a></td>
                            <td class="w20">17</td>
                            <td class="w20">3</td>
                            <td class="w20">4</td>
                            <td class="w60">54</td>
                        </tr>
                    </table>
                    <div class="txt_view_more"><a href="#" class="txt_gray">Chi tiết bảng xếp hạng</a> <span class="icon_portal_thethao icon_view_more">&nbsp;</span></div>                         
                </div>
                <div class="content_tab tab3">
                    <table class="tb_bxh">
                        <tr class="top">
                            <td class="w150">Team</td>
                            <td class="w20">W</td>
                            <td class="w20">D</td>
                            <td class="w20">L</td>
                            <td class="w60">Pts</td>
                        </tr>
                        <tr class="top2">
                            <td class="w150"><a href="#" class="txt_black_hover_blue">Manchester United</a></td>
                            <td class="w20">17</td>
                            <td class="w20">3</td>
                            <td class="w20">4</td>
                            <td class="w60">54</td>
                        </tr>
                        <tr class="top2">
                            <td class="w150"><a href="#" class="txt_black_hover_blue">Manchester United</a></td>
                            <td class="w20">17</td>
                            <td class="w20">3</td>
                            <td class="w20">4</td>
                            <td class="w60">54</td>
                        </tr>
                        <tr class="top2">
                            <td class="w150"><a href="#" class="txt_black_hover_blue">Manchester United</a></td>
                            <td class="w20">17</td>
                            <td class="w20">3</td>
                            <td class="w20">4</td>
                            <td class="w60">54</td>
                        </tr>
                        <tr class="top3">
                            <td class="w150"><a href="#" class="txt_black_hover_blue">Manchester United</a></td>
                            <td class="w20">17</td>
                            <td class="w20">3</td>
                            <td class="w20">4</td>
                            <td class="w60">54</td>
                        </tr>
                        <tr class="top4">
                            <td class="w150"><a href="#" class="txt_black_hover_blue">Manchester United</a></td>
                            <td class="w20">17</td>
                            <td class="w20">3</td>
                            <td class="w20">4</td>
                            <td class="w60">54</td>
                        </tr>
                        <tr>
                            <td class="w150"><a href="#" class="txt_black_hover_blue">Manchester United</a></td>
                            <td class="w20">17</td>
                            <td class="w20">3</td>
                            <td class="w20">4</td>
                            <td class="w60">54</td>
                        </tr>
                        <tr>
                            <td class="w150"><a href="#" class="txt_black_hover_blue">Manchester United</a></td>
                            <td class="w20">17</td>
                            <td class="w20">3</td>
                            <td class="w20">4</td>
                            <td class="w60">54</td>
                        </tr>
                        <tr>
                            <td class="w150"><a href="#" class="txt_black_hover_blue">Manchester United</a></td>
                            <td class="w20">17</td>
                            <td class="w20">3</td>
                            <td class="w20">4</td>
                            <td class="w60">54</td>
                        </tr>
                        <tr>
                            <td class="w150"><a href="#" class="txt_black_hover_blue">Manchester United</a></td>
                            <td class="w20">17</td>
                            <td class="w20">3</td>
                            <td class="w20">4</td>
                            <td class="w60">54</td>
                        </tr>
                        <tr>
                            <td class="w150"><a href="#" class="txt_black_hover_blue">Manchester United</a></td>
                            <td class="w20">17</td>
                            <td class="w20">3</td>
                            <td class="w20">4</td>
                            <td class="w60">54</td>
                        </tr>
                    </table>
                    <div class="txt_view_more"><a href="#" class="txt_gray">Chi tiết bảng xếp hạng</a> <span class="icon_portal_thethao icon_view_more">&nbsp;</span></div>                         
                </div>
                <div class="content_tab tab4">
                    <table class="tb_bxh">
                        <tr class="top">
                            <td class="w150">Team</td>
                            <td class="w20">W</td>
                            <td class="w20">D</td>
                            <td class="w20">L</td>
                            <td class="w60">Pts</td>
                        </tr>
                        <tr class="top2">
                            <td class="w150"><a href="#" class="txt_black_hover_blue">Manchester United</a></td>
                            <td class="w20">17</td>
                            <td class="w20">3</td>
                            <td class="w20">4</td>
                            <td class="w60">54</td>
                        </tr>
                        <tr class="top2">
                            <td class="w150"><a href="#" class="txt_black_hover_blue">Manchester United</a></td>
                            <td class="w20">17</td>
                            <td class="w20">3</td>
                            <td class="w20">4</td>
                            <td class="w60">54</td>
                        </tr>
                        <tr class="top2">
                            <td class="w150"><a href="#" class="txt_black_hover_blue">Manchester United</a></td>
                            <td class="w20">17</td>
                            <td class="w20">3</td>
                            <td class="w20">4</td>
                            <td class="w60">54</td>
                        </tr>
                        <tr class="top3">
                            <td class="w150"><a href="#" class="txt_black_hover_blue">Manchester United</a></td>
                            <td class="w20">17</td>
                            <td class="w20">3</td>
                            <td class="w20">4</td>
                            <td class="w60">54</td>
                        </tr>
                        <tr class="top4">
                            <td class="w150"><a href="#" class="txt_black_hover_blue">Manchester United</a></td>
                            <td class="w20">17</td>
                            <td class="w20">3</td>
                            <td class="w20">4</td>
                            <td class="w60">54</td>
                        </tr>
                        <tr>
                            <td class="w150"><a href="#" class="txt_black_hover_blue">Manchester United</a></td>
                            <td class="w20">17</td>
                            <td class="w20">3</td>
                            <td class="w20">4</td>
                            <td class="w60">54</td>
                        </tr>
                        <tr>
                            <td class="w150"><a href="#" class="txt_black_hover_blue">Manchester United</a></td>
                            <td class="w20">17</td>
                            <td class="w20">3</td>
                            <td class="w20">4</td>
                            <td class="w60">54</td>
                        </tr>
                        <tr>
                            <td class="w150"><a href="#" class="txt_black_hover_blue">Manchester United</a></td>
                            <td class="w20">17</td>
                            <td class="w20">3</td>
                            <td class="w20">4</td>
                            <td class="w60">54</td>
                        </tr>
                        <tr>
                            <td class="w150"><a href="#" class="txt_black_hover_blue">Manchester United</a></td>
                            <td class="w20">17</td>
                            <td class="w20">3</td>
                            <td class="w20">4</td>
                            <td class="w60">54</td>
                        </tr>
                        <tr>
                            <td class="w150"><a href="#" class="txt_black_hover_blue">Manchester United</a></td>
                            <td class="w20">17</td>
                            <td class="w20">3</td>
                            <td class="w20">4</td>
                            <td class="w60">54</td>
                        </tr>
                    </table>
                    <div class="txt_view_more"><a href="#" class="txt_gray">Chi tiết bảng xếp hạng</a> <span class="icon_portal_thethao icon_view_more">&nbsp;</span></div>                         
                </div>
            </div>
        </div>
        <div id="box_lichthidau_bongda" class="box_col_300 box_width_common left">
            <div class="txt_title_box">Lịch thi đấu</div>
            <div class="content_news">
                <div class="content_tab">
                    <table class="tb_lichthidau">
                        <tr class="top">
                            <td colspan="2"> Ngoại hạng anh</td>
                        </tr>
                        <tr>
                            <td class="w80">04/02  20:00</td>
                            <td class="w180">Man Utd - Liverpool</td>
                        </tr>
                        <tr class="chan">
                            <td class="w80">04/02  20:00</td>
                            <td class="w180">Man Utd - Liverpool</td>
                        </tr>
                        <tr>
                            <td class="w80">04/02  20:00</td>
                            <td class="w180">Man Utd - Liverpool</td>
                        </tr>
                        <tr class="chan">
                            <td class="w80">04/02  20:00</td>
                            <td class="w180">Man Utd - Liverpool</td>
                        </tr>
                        <tr>
                            <td class="w80">04/02  20:00</td>
                            <td class="w180">Man Utd - Liverpool</td>
                        </tr>
                        <tr class="chan">
                            <td class="w80">04/02  20:00</td>
                            <td class="w180">Man Utd - Liverpool</td>
                        </tr>
                        <tr>
                            <td class="w80">04/02  20:00</td>
                            <td class="w180">Man Utd - Liverpool</td>
                        </tr>
                        <tr class="chan">
                            <td class="w80">04/02  20:00</td>
                            <td class="w180">Man Utd - Liverpool</td>
                        </tr>
                    </table>
                    <table class="tb_lichthidau">
                        <tr class="top">
                            <td colspan="2">Primera - Tây Ban Nha</td>
                        </tr>
                        <tr>
                            <td class="w80">04/02  20:00</td>
                            <td class="w180">Man Utd - Liverpool</td>
                        </tr>
                        <tr class="chan">
                            <td class="w80">04/02  20:00</td>
                            <td class="w180">Man Utd - Liverpool</td>
                        </tr>
                        <tr>
                            <td class="w80">04/02  20:00</td>
                            <td class="w180">Man Utd - Liverpool</td>
                        </tr>
                        <tr class="chan">
                            <td class="w80">04/02  20:00</td>
                            <td class="w180">Man Utd - Liverpool</td>
                        </tr>
                        <tr>
                            <td class="w80">04/02  20:00</td>
                            <td class="w180">Man Utd - Liverpool</td>
                        </tr>
                        <tr class="chan">
                            <td class="w80">04/02  20:00</td>
                            <td class="w180">Man Utd - Liverpool</td>
                        </tr>
                    </table>
                    <div class="txt_view_more"><a href="#" class="txt_gray">Xem thêm</a> <span class="icon_portal_thethao icon_view_more">&nbsp;</span></div>                         
                </div>
            </div>
        </div>
        <div id="box_chandung" class="box_col_300 box_width_common left">
            <div class="txt_title_box">Chân dung</div>
            <div class="content_news">
                <div class="block_chandung">
                    <!--<div class="img_chandung">
                            <a href="#" title="chan dung">
                                    <img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_280x210.jpg" alt="" />
                            <span class="txt_intro_chandung">Tevez bị ghẻ lạnh trong ngày trở lại Man City </span>
                        </a>
                    </div>
                    <div class="con_ul">   
            <ul>			
                    <li alt="Nghĩa" value="3" rel="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_flash.jpg"  id="0" class="thumb item active" title="&nbsp;">
                                                    <a onclick="return false;" href="#" target="_blank">
                                                    1</a>                        	</li>							
                    <li alt="Đức" value="1" rel="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_flash.jpg"  id="1" class="thumb item" title="&nbsp;">
                                                    <a onclick="return false;" href="#" target="_blank">
                                                    2</a>                        	</li>													
                                                                                                            
                    <li alt="minhchieu660" rel="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_flash.jpg"  value="1" id="2" class="thumb item" title="&nbsp;">
                                                    <a onclick="return false;" href="#" target="_blank">
                                                    3</a>                        	</li>												
                                                                                                            
                    <li alt="Phi" value="1" rel="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_flash.jpg"  id="3" class="thumb item end" title="&nbsp;">
                                                    <a onclick="return false;" href="#" target="_blank">
                                                    4</a>                        
                </li>													
                            </ul>
            </div>-->
                    <div id="hot_img">
                        <div class="slide_img">
                            <div id="imgLink" style="display: block;">                        </div>
                        </div>
                        <div class="txt_top">
                            <p class="title_text" id="descPhoto" style="display: block;"></p>	

                        </div>
                        <div class="con_ul">   
                            <ul>			
                                <li alt="Nghĩa" value="3" rel="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_280x210.jpg"  class="thumb item active" title="Tevez bị ghẻ lạnh trong ngày trở lại Man City 123">
                                    <a onclick="return false;" href="#" target="_blank">
                                        &nbsp;</a>                        	
                                </li>							
                                <li alt="Đức" value="1" rel="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_280x210.jpg" class="thumb item" title="Tevez bị ghẻ lạnh trong ngày trở lại Man City 456">
                                    <a onclick="return false;" href="#" target="_blank">
                                        &nbsp;</a>  
                                </li>	
                                <li alt="Nghĩa" value="3" rel="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_280x210.jpg"  class="thumb item active" title="Tevez bị ghẻ lạnh trong ngày trở lại Man City 123">
                                    <a onclick="return false;" href="#" target="_blank">
                                        &nbsp;</a>                        	
                                </li>							
                                <li alt="Đức" value="1" rel="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_280x210.jpg" class="thumb item" title="Tevez bị ghẻ lạnh trong ngày trở lại Man City 456">
                                    <a onclick="return false;" href="#" target="_blank">
                                        &nbsp;</a>  
                                </li>											
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="clear">&nbsp;</div>
            </div>
        </div>
        <div id="box_suervey" class="box_col_300 box_width_common left">
            <div class="txt_title_box">Thăm dò ý kiến</div>
            <div class="content_news">
                <div class="txt_suervey dot_bottom">
                    <p>Theo bạn, ai sẽ là đội trưởng tiếp theo của Đội Tuyển Anh ?</p>
                </div>
                <div class="input_suervey">
                    <ul>
                        <li><input type="radio" name="noname" id="name1"/><label for="name1">Frank Lampard</label></li>
                        <li><input type="radio" name="noname" id="name2"/><label for="name2">Frank Lampard</label></li>
                        <li><input type="radio" name="noname" id="name3"/><label for="name3">Frank Lampard</label></li>
                        <li><input type="submit" value="Bình chọn" class="btn_submit"/><a href="#" class="txt_black_hover_blue"><b>Kết quả</b></a></li>
                    </ul>
                </div>
                <div class="clear">&nbsp;</div>
            </div>
        </div>
        <div id="box_social_plugin"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_social_plugin.jpg" alt=""/></div>
        <!-- InstanceEndEditable --> 
    </div>
</div>