<div id="breackcumb_portal" class="w980 left">

    <div class="left">
        <div class="title_vne_portal">
            <!-- InstanceBeginEditable name="breakcumb" -->
            <p><a href="#" title="vne portal the thao"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_vne_thethao.jpg" alt="" /></a></p>

            <!-- InstanceEndEditable -->
        </div>
    </div>
    <div class="right">
        <div class="w300 right">
            <div class="hot_match">
                <a href="#" title="ten doi bong"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_doibong.jpg" class="img_doibong" alt=""/></a>
                <div class="w180 match_info">
                    <b class="txt_blue">Manchester Utd - Barcelona</b><br />
                    <span class="txt_gray">10/02/2012 | 19:45 -</span> <a href="#">Sopcast link</a>
                </div>
                <a href="#" title="ten doi bong"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/img_doibong.jpg" class="img_doibong" alt=""/></a>
            </div>
        </div>
    </div>

</div>