<div id="block_product_footer">
    <div class="btn_left"><a href="javascript:;">&nbsp;</a></div>
    <div class="main_block">
        <ul>
            <li class="start"><span class="inline_block news">&nbsp;</span><a href="#">Tin tức</a></li>
            <li><a href="#">Tin tức</a></li>
            <li><a href="#">Video</a></li>
            <li><a href="#">Hình ảnh</a></li>
            <li><a href="#">Xã hội</a></li>
            <li><a href="#">Thế giới </a></li>
            <li><a href="#">Kinh doanh</a></li>
            <li><a href="#">Văn hóa</a></li>
            <li><a href="#">Thể thao</a></li>
            <li><a href="#">Pháp luật</a></li>
            <li><a href="#">Đời sống</a></li>
            <li><a href="#">Khoa học</a></li>
            <li><a href="#">Vi tính</a></li>
        </ul>
        <ul>
            <li class="start"><span class="inline_block enteraiment">&nbsp;</span><a href="#">Giải trí</a></li>
            <li><a href="#">Hoa hậu</a></li>
            <li><a href="#">Nghệ sĩ</a></li>
            <li><a href="#">Điện ảnh</a></li>
            <li><a href="#">Mỹ thuật </a></li>
            <li><a href="#">Âm nhạc</a></li>
            <li><a href="#">Hậu trường</a></li>
            <li><a href="#">Thời cuộc</a></li>
            <li><a href="#">Phong cách</a></li>
            <li><a href="#">Thư giãn</a></li>
            <li><a href="#">Cưới</a></li>
            <li><a href="#">Góc độc giả</a></li>
            <li><a href="#">Thư viện giải trí</a></li>
        </ul>
        <ul>
            <li class="start"><span class="inline_block tech">&nbsp;</span><a href="#">Công nghệ</a></li>
            <li><a href="#">iOS</a></li>
            <li><a href="#">Android</a></li>
            <li><a href="#">BlackBerry</a></li>
            <li><a href="#">Điện thoại</a></li>
            <li><a href="#">Máy tính</a></li>
            <li><a href="#">Camera</a></li>
            <li><a href="#">Hình ảnh</a></li>
            <li><a href="#">Đồ chơi số</a></li>
            <li><a href="#">Âm thanh</a></li>
            <li><a href="#">Tư vấn</a></li>
            <li><a href="#">Cộng đồng Số Hóa</a></li>
            <li><a href="#">Số hóa bình chọn</a></li>
        </ul>
        <ul>
            <li class="start"><span class="inline_block youngs">&nbsp;</span><a href="#">Giới trẻ </a></li>
            <li><a href="#">Nhịp sống</a></li>
            <li><a href="#">Showbiz</a></li>
            <li><a href="#">Thời trang</a></li>
            <li><a href="#">Học đường </a></li>
            <li><a href="#">Giới tính</a></li>
            <li><a href="#">Thể thao</a></li>
            <li><a href="#">Tự chế</a></li>
            <li><a href="#">Ba lô</a></li>
            <li><a href="#">Vui độc</a></li>
            <li><a href="#">Hi-tek</a></li>
            <li><a href="#">iShare</a></li>
            <li><a href="#">Quà tặng</a></li>
        </ul>
        <ul>
            <li class="start"><span class="inline_block sport">&nbsp;</span><a href="#">Thể thao</a></li>
            <li><a href="#">Tin tức</a></li>
            <li><a href="#">Bóng đá</a></li>
            <li><a href="#">Bóng đá Anh</a></li>
            <li><a href="#">Bóng đá TBN</a></li>
            <li><a href="#">Bóng đá Ý</a></li>
            <li><a href="#">Euro 2012</a></li>
            <li><a href="#">Thế giới bóng đá</a></li>
            <li><a href="#">Bóng đá Việt Nam</a></li>
            <li><a href="#">Video bàn thắng</a></li>
            <li><a href="#">Hình ảnh</a></li>
            <li><a href="#">CLB Bóng đá</a></li>
            <li><a href="#">Tennis</a></li>
        </ul>

        <ul>
            <li class="start"><span class="inline_block finance">&nbsp;</span><a href="#">Tài chính</a></li>
            <li><a href="#">Sóng tài chính</a></li>
            <li><a href="#">Thế giới phẳng</a></li>
            <li><a href="#">Đầu tư</a></li>
            <li><a href="#">Tiền của tôi </a></li>
            <li><a href="#">Diễn đàn</a></li>
            <li><a href="#">Ngân hàng</a></li>
            <li><a href="#">Tin chứng khoán</a></li>
            <li><a href="#">Tỷ giá ngoại tệ</a></li>
            <li><a href="#">Giá vàng hôm nay</a></li>
            <li><a href="#">Bảng giá Chứng khoán</a></li>
            <li><a href="#">Chung cư </a></li>
            <li><a href="#">Nhà đất</a></li>
        </ul>
    </div>
    <div class="btn_right"><a href="javascript:;">&nbsp;</a></div>
</div>
<div class="coppy_right">
    <div class="logo"><a href="#" title="vnexpress.net"><img src="images/graphics/img_vnexpress.jpg" width="180" alt="vnexpress.net" /></a></div>
    <div class="txt_coppy_right">© <b>Copyright 1997-2011 VnExpress.net</b>, All rights reserved Contact us <br />
        ® VnExpress giữ bản quyền nội dung trên website này. Thông tin tòa soạn</div>
    <div class="txx_right_footer"> <a href="#">VnExpress tuyển dụng</a> &nbsp; | &nbsp; <a href="#">Liên hệ quảng cáo</a> &nbsp; | &nbsp;<a href="#">Liên hệ tòa soạn</a><br />
        Đường dây nóng:<b>0123.888.0123</b> (HN) - <b>0129.233.3555</b> (TP HCM) </div>
</div>
<script language="javascript" type="text/javascript">
    $(function(){
        $('#slides_video').slides({
            preload: true,
            preloadImage: 'img/loading.gif',
            play: 5000,
            pause: 500,
            hoverPause: true,
            animationStart: function(current){
                $('.caption').animate({
                    bottom:-35
                },100);
                if (window.console && console.log) {
                    // example return of current slide number
                    console.log('animationStart on slide: ', current);
                };
            },
            animationComplete: function(current){
                $('.caption').animate({
                    bottom:0
                },200);
                if (window.console && console.log) {
                    // example return of current slide number
                    console.log('animationComplete on slide: ', current);
                };
            },
            slidesLoaded: function() {
                $('.caption').animate({
                    bottom:0
                },200);
            }
        });
	
        $('#slides_photo').slides({
            preload: true,
            preloadImage: 'img/loading.gif',
            play: 5000,
            pause: 500,
            hoverPause: true,
            animationStart: function(current){
                $('.caption').animate({
                    bottom:-35
                },100);
                if (window.console && console.log) {
                    // example return of current slide number
                    console.log('animationStart on slide: ', current);
                };
            },
            animationComplete: function(current){
                $('.caption').animate({
                    bottom:0
                },200);
                if (window.console && console.log) {
                    // example return of current slide number
                    console.log('animationComplete on slide: ', current);
                };
            },
            slidesLoaded: function() {
                $('.caption').animate({
                    bottom:0
                },200);
            }
        });
        $('#box_video_hot .tab2').hide();
    });
</script>