<div class="menu_site">
    <ul class="main_menu">
        <li class="start"><a href="#" class="parent_menu">Tin tức</a>
            <div id="menu_tab1" class="menu_site_sub">
                <ul class="main_menu_sub">
                    <li  class="active"><a class="txt_black_hover_blue" href="#">Tin tức Hội Đồng Hương</a></li>
                    <li><a class="txt_black_hover_blue" href="#">Tin tức Quê nhà</a></li>
                    <li><a class="txt_black_hover_blue" href="#">Đức</a></li>
                    <li><a class="txt_black_hover_blue" href="#">Các giải khác</a></li> 
                </ul> 
            </div>
        </li>
        <li class="active"><a href="#" class="parent_menu">Danh sách thành viên</a><div id="menu_tab2" class="menu_site_sub">
                <ul class="main_menu_sub">
                    <li><a class="txt_black_hover_blue" href="#">Tin tức chuyển nhượng</a></li>
                    <li><a class="txt_black_hover_blue" href="#">Tây Ban Nha</a></li>
                    <li class="active"><a class="txt_black_hover_blue" href="#">Đức</a></li>
                    <li><a class="txt_black_hover_blue" href="#">Các giải khác</a></li> 
                </ul> 
            </div></li>
        <li><a href="#" class="parent_menu">Hình ảnh</a><div id="menu_tab3" class="menu_site_sub">
                <ul class="main_menu_sub">
                    <li><a class="txt_black_hover_blue" href="#">Tin tức chuyển nhượng</a></li><li><a class="txt_black_hover_blue" href="#">Tây Ban Nha</a></li>
                    <li class="active"><a class="txt_black_hover_blue" href="#">Đức</a></li>
                    <li><a class="txt_black_hover_blue" href="#">Các giải khác</a></li> 
                </ul> 
            </div></li>
        <li><a href="#" class="parent_menu">Video</a> <div id="menu_tab4" class="menu_site_sub">
                <ul class="main_menu_sub">
                    <li><a class="txt_black_hover_blue" href="#">Tin tức chuyển nhượng</a></li><li><a class="txt_black_hover_blue" href="#">Tây Ban Nha</a></li>
                    <li class="active"><a class="txt_black_hover_blue" href="#">Đức</a></li>
                    <li><a class="txt_black_hover_blue" href="#">Các giải khác</a></li> 
                </ul> 
            </div>
        </li>
        <li><a href="#" class="parent_menu">Lịch sử - Văn hóa</a> <div id="menu_tab5" class="menu_site_sub">
                <ul class="main_menu_sub">
                    <li><a class="txt_black_hover_blue" href="#">Tin tức chuyển nhượng</a></li><li><a class="txt_black_hover_blue" href="#">Tây Ban Nha</a></li>
                    <li class="active"><a class="txt_black_hover_blue" href="#">Đức</a></li>
                    <li><a class="txt_black_hover_blue" href="#">Các giải khác</a></li> 
                </ul> 
            </div></li>
        <li><a href="#" class="parent_menu">Lịch thi đấu</a> <div id="menu_tab6" class="menu_site_sub">
                <ul class="main_menu_sub">
                    <li><a class="txt_black_hover_blue" href="#">Tin tức chuyển nhượng</a></li><li><a class="txt_black_hover_blue" href="#">Tây Ban Nha</a></li>
                    <li class="active"><a class="txt_black_hover_blue" href="#">Đức</a></li>
                    <li><a class="txt_black_hover_blue" href="#">Các giải khác</a></li> 
                </ul> 
            </div></li>
        <li><a href="#" class="parent_menu">Chân dung</a> <div id="menu_tab7" class="menu_site_sub">
                <ul class="main_menu_sub">
                    <li><a class="txt_black_hover_blue" href="#">Tin tức chuyển nhượng</a></li><li><a class="txt_black_hover_blue" href="#">Tây Ban Nha</a></li>
                    <li class="active"><a class="txt_black_hover_blue" href="#">Đức</a></li>
                    <li><a class="txt_black_hover_blue" href="#">Các giải khác</a></li> 
                </ul> 
            </div></li>
        <li><a href="#" class="parent_menu"> Bạn đọc</a> <div id="menu_tab8" class="menu_site_sub">
                <ul class="main_menu_sub">
                    <li><a class="txt_black_hover_blue" href="#">Tin tức chuyển nhượng</a></li><li><a class="txt_black_hover_blue" href="#">Tây Ban Nha</a></li>
                    <li class="active"><a class="txt_black_hover_blue" href="#">Đức</a></li>
                    <li><a class="txt_black_hover_blue" href="#">Các giải khác</a></li> 
                </ul> 
            </div>
        </li>
    </ul>
</div>
<div class="sub_title_menu">
    <div id="search_bar">
        <input type="text" class="w190 txt_search" />
        <input value="" type="submit" class="btn_search" />
    </div>
    <div class="rss"><a href="#" class="icon_portal_thethao icon_rss" title="rss">&nbsp;</a></div>
</div>