<div id="ionetaskbar_top">
            <div id="top_page">
                <div id="main_top">
                    <ul class="left">
                        <li class="start"><a href="#">vnExpress</a></li>
                        <li><a href="#">Ngôi Sao</a></li>
                        <li class="active"><a href="#">Bạn Bè</a></li>
                        <li><a href="#">Nhạc Số</a></li>
                        <li><a href="#">Gate</a></li>
                        <li class="more"><a href="#" id="hasmore">Thêm <img src="images/graphics/blank_img.gif" width="7" class="arrow" height="10"/></a>
                            <div id="subtop">
                                <div class="content_subtop"> <a href="#">Vitalk</a> <a href="#">Số Hóa</a> <a href="#">Gate</a> <a href="#">Sản phẩm khác</a> </div>
                            </div>
                        </li>
                    </ul>
                    <div class="right">
                        <div class="nav-right">
                            <ul class="mynaviga">
                                <li><a href="#"><img src="<?php echo TEMPLATE_URL ?>/default/images/graphics/20x20/_img1.jpg" alt="" height="20" width="20" class="photo-left-06" />Andy Le</a></li>
                                <li class="tk"> <a href="#">Tài khoản <span class="arrow-bottom">&nbsp;</span></a>
                                    <ul>
                                        <li><span class="icon01 ico35 left">&nbsp;</span><a href="#">Tin nhắn</a></li>
                                        <li><span class="icon01 ico34 left">&nbsp;</span><a href="#">Quản lý bạn bè</a></li>
                                        <li><span class="icon01 ico68 left">&nbsp;</span><a href="#">Quản lý Pages</a></li>
                                        <li><span class="icon01 ico70 left">&nbsp;</span><a href="#">Thay đổi mật khẩu</a></li>
                                        <li><span class="icon01 ico71 left">&nbsp;</span><a href="#">Cập nhật thông tin</a></li>
                                        <li><span class="icon01 ico37 left">&nbsp;</span><a href="#">Thiếp lập quyền riêng tư</a></li>
                                        <li><span class="icon01 ico72 left">&nbsp;</span><a href="#">Thiếp lập thông báo</a></li>
                                        <li><span class="icon01 ico38 left">&nbsp;</span><a href="#">Thiết lập tài khoản</a></li>
                                        <li><span class="icon01 ico36 left">&nbsp;</span><a href="#">Thoát</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>